#include <stdio.h>
#include <string.h>
int main()
{
    int i,j1,j2,len1,len2,p,q1,d1,d2,c1,c2;
    char a[50024],b[50024],a1[50024],a2[50024],b1[50024],b2[50024];
    while(~scanf("%s %s",a,b))
    {
        memset(a1,0,sizeof(a1));
        memset(a2,0,sizeof(a2));
        memset(b1,0,sizeof(b1));
        memset(b2,0,sizeof(b2));
        len1=strlen(a);
        p=0;
        q1=1;
        j1=0;
        j2=0;
        for(i=0;i<len1;i++)
        {
            if(a[i]=='.')
            {
                p=1;
                continue;
            }
            if(p)
            {
                a2[j2]=a[i];
                j2++;
            }
            else
            {
                if(a[i]=='0'&&q1)
                    continue;
                else
                {
                    a1[j1]=a[i];
                    j1++;
                    q1=0;
                }
            }
        }
        len2=strlen(b);
        p=0;
        q1=1;
        j1=0;
        j2=0;
        for(i=0;i<len2;i++)
        {
            if(b[i]=='.')
            {
                p=1;
                continue;
            }
            if(p)
            {
                b2[j2]=b[i];
                j2++;
            }
            else
            {
                if(b[i]=='0'&&q1)
                    continue;
                else
                {
                    b1[j1]=b[i];
                    j1++;
                    q1=0;
                }
            }
        }
        d1=d2=0;
        c1=strlen(a2);
        c2=strlen(b2);
        if(c1<=c2)
        {
            for(i=c1;i<c2;i++)
            a2[i]='0';
        }
        else
        {
            for(i=c2;i<c1;i++)
                b2[i]='0';
        }
        if(strcmp(a1,b1)==0)
            d1=1;
        if(strcmp(a2,b2)==0)
            d2=1;
        if(d1&&d2)
            printf("YES\n");
        else
            printf("NO\n");
    }
    return 0;
}
